#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id		bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dnumber		text,
    name		text,
    description		text,
    status		smallint default 1,
    id_basis		bigint,
    prefix		smallint,
    id_transaction		text,
    id_user		bigint,
UNIQUE (id, id_basis)
  );

  COMMENT ON TABLE  ${DB_TABLENAME} IS 'Reasons For The Dcs Disagreement';
  COMMENT ON COLUMN ${DB_TABLENAME}.id IS 'Id';
  COMMENT ON COLUMN ${DB_TABLENAME}.dnumber IS 'Dnumber';
  COMMENT ON COLUMN ${DB_TABLENAME}.name IS 'Name';
  COMMENT ON COLUMN ${DB_TABLENAME}.description IS 'Description';
  COMMENT ON COLUMN ${DB_TABLENAME}.status IS 'Status';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_basis IS 'Id Basis';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix IS 'Prefix';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction IS 'Id Transaction';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_user IS 'Id User';
EOSQL
