#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance              smallint NOT NULL,
    id_document          bigint NOT NULL,
    ddate                timestamp,
	prefix               smallint,
    name                 text,
    id_job_title         bigint NOT NULL,
    id_transaction       text,
    UNIQUE (id_document, id_job_title)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                      IS 'Department data ledger';
  COMMENT ON COLUMN ${DB_TABLENAME}.id                   IS 'Lager ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.balance              IS 'Balance';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_document          IS 'Transaction document';
  COMMENT ON COLUMN ${DB_TABLENAME}.ddate                IS 'Document date';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix               IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.name                 IS 'Name';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_job_title         IS 'Job title ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction       IS 'Transaction Id';

EOSQL
