#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance              smallint NOT NULL,
    id_document          bigint NOT NULL,
    ddate                timestamp,
	prefix               smallint,
	id_employee          bigint NOT NULL,
    first_name           text,
    last_name            text,
    middle_name          text,
    first_genitive       text,
    last_genitive        text,
    middle_genitive      text,
    first_accusative     text,
    last_accusative      text,
    middle_accusative    text,
    id_vk                bigint,
    id_transaction       text,
    UNIQUE (id_document, id_employee)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                      IS 'Employee data ledger';
  COMMENT ON COLUMN ${DB_TABLENAME}.id                   IS 'Lager ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.balance              IS 'Balance';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_document          IS 'Transaction document';
  COMMENT ON COLUMN ${DB_TABLENAME}.ddate                IS 'Document date';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix               IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_employee          IS 'Employee ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.first_name           IS 'Name';
  COMMENT ON COLUMN ${DB_TABLENAME}.last_name            IS 'Surname';
  COMMENT ON COLUMN ${DB_TABLENAME}.middle_name          IS 'Patronymic';
  COMMENT ON COLUMN ${DB_TABLENAME}.first_genitive       IS 'Name in the genitive case';
  COMMENT ON COLUMN ${DB_TABLENAME}.last_genitive        IS 'Surname in the genitive case';
  COMMENT ON COLUMN ${DB_TABLENAME}.middle_genitive      IS 'Patronymic in the genitive case';
  COMMENT ON COLUMN ${DB_TABLENAME}.first_accusative     IS 'Name in the accusative case';
  COMMENT ON COLUMN ${DB_TABLENAME}.last_accusative      IS 'Surname in the accusative case';
  COMMENT ON COLUMN ${DB_TABLENAME}.middle_accusative    IS 'Patronymic in the accusative case';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_vk                IS 'VK Id';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction       IS 'Transaction Id';

EOSQL
