import os
import subprocess
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent

SOURCE_DIR = PROJECT_ROOT / "source"
DOCKERFILES_DIR = PROJECT_ROOT / "Dockerfiles"


def generate_main_go(ms_name):
    return f'''package main

import (
	"{ms_name}/model"
	"shared/app"
)

func main() {{
	var a app.App[model.Object]
	a.CreateConnection()
	a.CreateRoutes()
}}
'''


def generate_go_mod(ms_name):
    return f'''module {ms_name}

go 1.26.0
'''


def generate_parameters_env(ref, db_host, db_user, table_name):
    return f'''POSTGRES_PASSWORD=Yy5U%]%6,ep>t:WhfWo
DB_PASSWORD=Y8W?6F.I46yI
DB_HOST={db_host}
DB_PORT=5434
DB_NAME=psadmin
DB_USER={db_user}
DB_TABLENAME={table_name}
APP_PORT=8443
'''


def generate_model_go(fields, ref):
    lines = ["package model", "", "import (", "\t\"time\"", ")", ""]
    # Only import time if needed
    has_time = any(f["go_type"] == "time.Time" for f in fields)
    if not has_time:
        lines = ["package model", "", ""]

    lines.append(f"// {ref.replace('_', ' ').title()} model")
    lines.append("type Object struct {")

    for f in fields:
        gorm_parts = [f"column:{f['column']}"]
        if f.get("is_pk"):
            gorm_parts.append("primaryKey")
        if f.get("is_auto_increment"):
            gorm_parts.append("autoIncrement")
        gorm_str = ";".join(gorm_parts)
        json_str = f["json_name"]
        lines.append(f"\t{f['name']}\t\t{f['go_type']}\t`gorm:\"{gorm_str}\" json:\"{json_str}\"`")

    lines.append("}")
    lines.append("")
    lines.append("func (o *Object) GetID() int64 {")
    lines.append("\treturn o.Id")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_db_sh(table_name, fields, category, db_user):
    col_lines = []
    comment_lines = []

    ref_field = "id_basis" if category in ("directory", "document") else "id_document"
    unique_cols = ["id", ref_field] if category != "ledger" else ["id_document", "id_employee"]

    for f in fields:
        nullable = "" if f.get("not_null") else ""
        default = ""
        if f.get("column") == "status":
            default = " default 1"

        pk_part = ""
        if f.get("is_pk") and f.get("is_auto_increment"):
            pk_part = " GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        elif f.get("is_pk"):
            pk_part = " PRIMARY KEY"

        col_lines.append(f"    {f['column']}\t\t{f['sql_type']}{nullable}{default}{pk_part},")

        label = f.get("json_name", f["column"]).replace("_", " ").title()
        comment_lines.append(f"  COMMENT ON COLUMN ${{DB_TABLENAME}}.{f['column']} IS '{label}';")

    cols_str = "\n".join(col_lines)
    comments_str = "\n".join(comment_lines)
    unique_str = f"UNIQUE ({', '.join(unique_cols)})" if unique_cols else ""

    return f'''#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${{DB_NAME}};
  CREATE USER ${{DB_USER}} WITH PASSWORD '${{DB_PASSWORD}}';
  GRANT ALL PRIVILEGES ON DATABASE ${{DB_NAME}} TO ${{DB_USER}};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${{DB_NAME}}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${{DB_USER}};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${{DB_USER}}" --dbname "${{DB_NAME}}" <<-EOSQL
  CREATE TABLE public.${{DB_TABLENAME}} (
{cols_str}
{unique_str}
  );

  COMMENT ON TABLE  ${{DB_TABLENAME}} IS '{table_name.replace("_", " ").title()}';
{comments_str}
EOSQL
'''


def get_services_grouped():
    """Return dict of category -> list of ms_names from go.work + project_reader."""
    try:
        from project_reader import read_all_microservices
        services = read_all_microservices()
    except ImportError:
        services = []
    grouped = {"directory": [], "document": [], "ledger": []}
    for s in services:
        cat = s["category"]
        if cat in grouped:
            grouped[cat].append(s["name"])
    for cat in grouped:
        grouped[cat] = sorted(set(grouped[cat]))
    return grouped


def generate_dockerfile(category, ms_name, all_services=None):
    """Generate Dockerfile that lists ALL microservices (monorepo build pattern)."""
    if all_services is None:
        all_services = get_services_grouped()

    # Ensure the new service is included in its category
    if ms_name not in all_services.get(category, []):
        all_services.setdefault(category, []).append(ms_name)
        all_services[category] = sorted(all_services[category])

    lines = [
        "FROM golang:1.26-alpine AS builder",
        "WORKDIR /app",
        "",
        "# Сначала копируем файлы модулей для кэширования слоев",
        "#",
        "# Копируем go.mod и go.sum ОБОИХ проектов",
    ]

    for cat in ("directory", "document", "ledger"):
        names = all_services.get(cat, [])
        if names:
            if lines and not lines[-1].startswith("#"):
                lines.append("")
            for n in names:
                lines.append(f"COPY ./source/{cat}/{n}/go.mod ./{cat}/{n}/")

    lines.append("")
    lines.append("")
    lines.append("COPY ./source/shared/go.mod ./shared/")
    lines.append("COPY ./source/shared/go.sum ./shared/")
    lines.append("")
    lines.append("COPY ./source/go.work ./")
    lines.append("COPY ./source/go.work.sum ./")
    lines.append("")
    lines.append("# Копируем исходники")

    for cat in ("directory", "document", "ledger"):
        names = all_services.get(cat, [])
        if names:
            lines.append("")
            for n in names:
                lines.append(f"COPY ./source/{cat}/{n}/ ./{cat}/{n}/")

    lines.append("")
    lines.append("")
    lines.append("COPY ./source/shared/ ./shared/")
    lines.append("")
    lines.append(f"WORKDIR /app/{category}/{ms_name}")
    lines.append("# Собираем бинарный файл")
    lines.append("RUN CGO_ENABLED=0 GOOS=linux go build -v -o main .")
    lines.append("")
    lines.append("# Финальный минимальный образ (Distroless или Alpine)")
    lines.append("#FROM alpine:latest")
    lines.append("#WORKDIR /root/")
    lines.append("#COPY --from=builder /app/main .")
    lines.append('#ENTRYPOINT ["./main"]')
    lines.append('CMD ["./main"]')
    lines.append("")

    return "\n".join(lines)


def update_all_dockerfiles(ref, category):
    """Add new service's go.mod and source COPY lines to all existing Dockerfiles."""
    ms_name = f"ms_{ref}"
    dockerfiles_dir = PROJECT_ROOT / "Dockerfiles"
    updated = []
    for df_path in sorted(dockerfiles_dir.iterdir()):
        if not df_path.name.startswith("ms_") or df_path.name == ms_name:
            continue
        if df_path.is_dir():
            continue
        content = df_path.read_text()

        # Check if already has this service
        if f"/{category}/{ms_name}/" in content:
            continue

        go_mod_line = f"COPY ./source/{category}/{ms_name}/go.mod ./{category}/{ms_name}/"
        source_line = f"COPY ./source/{category}/{ms_name}/ ./{category}/{ms_name}/"

        # Find the go.mod section for this category and add the new go.mod line
        # Pattern: after the last go.mod COPY for this category, before the next category
        cat_pattern = f"COPY ./source/{category}/"
        # Find the last line of go.mod copies for this category
        lines = content.split("\n")
        last_go_mod_idx = -1
        last_source_idx = -1
        for i, line in enumerate(lines):
            if line.startswith(f"COPY ./source/{category}/") and line.endswith("/go.mod"):
                last_go_mod_idx = i
            if line.startswith(f"COPY ./source/{category}/") and line.endswith("/"):
                last_source_idx = i

        changed = False
        if last_go_mod_idx >= 0:
            lines.insert(last_go_mod_idx + 1, go_mod_line)
            last_source_idx += 1  # Shift after insert
            changed = True
        if last_source_idx >= 0:
            lines.insert(last_source_idx + 1, source_line)
            changed = True

        if changed:
            df_path.write_text("\n".join(lines) + "\n")
            updated.append(df_path.name)

    return updated


def get_db_user_from_ref(ref):
    return f"ms{ref}"


def get_ms_name_from_ref(ref):
    return f"ms_{ref}"


def get_category_name(category):
    return {"directory": "справочники", "document": "документы", "ledger": "регистры"}.get(category, category)


def indent(text, spaces=2):
    return "\n".join(" " * spaces + line if line else "" for line in text.splitlines())


def escape_sql(val):
    """Escape a value for SQL: double single quotes, wrap in single quotes."""
    s = str(val).replace("'", "''")
    return f"'{s}'"


def generate_table_columns_json(fields):
    """Generate table_columns JSON from field definitions.
    Skips fields marked exclude_from_table."""
    cols = []
    for f in fields:
        if f.get("exclude_from_table"):
            continue
        col = {
            "field": f.get("column", f["name"]),
            "label": f.get("ui_label", ""),
            "hidden": f.get("hidden", False) or f.get("is_pk", False),
        }
        cols.append(col)
    import json
    return json.dumps({"columns": cols}, ensure_ascii=False, indent=2)


def generate_item_fields_json(fields, category="directory"):
    """Generate item_fields JSON from field definitions.
    Excludes fields marked exclude_from_form.
    Always excludes status (workflow field managed by backend logic)."""
    system_cols = {"status"}
    items = []
    for f in fields:
        col = f.get("column", f["name"])
        if f.get("exclude_from_form") or col in system_cols:
            continue
        item = {
            "field": col,
            "label": f.get("ui_label", ""),
            "hidden": f.get("hidden", False) or f.get("is_pk", False),
            "required": f.get("not_null", False),
        }
        items.append(item)
    import json
    return json.dumps({"fields": items}, ensure_ascii=False, indent=2)


def generate_privileges_json():
    """Generate default privileges JSON (0-indent, fmt handles SQL indent)."""
    return """{
  "privileges": [
    { "open_list": "true" },
    { "open_item": "true" },
    { "create": "false" },
    { "edit": "false" },
    { "delete": "false" },
    { "accept": "false" },
    { "create_related_documents": "false" }
  ]
}"""


def generate_system_object_insert(name, description, ref, prefix, prefix_number,
                                   level, is_group, id_group, output_order, icon,
                                   table_title, item_title, fields, category="directory"):
    """Generate INSERT SQL for system_object_directory db.sh."""
    table_columns = generate_table_columns_json(fields) if not is_group else ""
    item_fields = generate_item_fields_json(fields, category) if not is_group else ""
    privileges = generate_privileges_json() if not is_group else ""

    cols = [
        "name", "description", "status", "prefix", "prefix_number",
        "level", "is_group", "id_group", "ref", "output_order", "icon",
        "table_columns", "table_title", "item_title", "item_fields",
        "on_save_new", "on_save_edit", "on_acceptance", "on_delete",
        "privileges", "related_documents", "printing_template", "id_transaction"
    ]

    def fmt(val):
        if isinstance(val, bool):
            return "TRUE" if val else "FALSE"
        if isinstance(val, int):
            return str(val)
        s = escape_sql(val)
        if "\n" in s:
            first, rest = s.split("\n", 1)
            rest = "\n".join("    " + l for l in rest.split("\n"))
            s = first + "\n" + rest
        return s

    values = [
        name, description, 1, prefix, prefix_number,
        level, is_group, id_group, ref, output_order, icon,
        table_columns, table_title, item_title, item_fields,
        "", "", "", "",
        privileges, "", "", ""
    ]
    col_str = ",\n    ".join(cols)
    val_str = ",\n    ".join(fmt(v) for v in values)
    return (
        "  insert into ${DB_TABLENAME}\n"
        "  (\n"
        f"    {col_str}\n"
        "  ) values (\n"
        f"    {val_str}\n"
        "  );\n"
    )


SYSTEM_OBJECT_DIR = (
    PROJECT_ROOT / "source" / "directory" / "ms_system_object_directory"
)
SYSTEM_OBJECT_DBSHELL = SYSTEM_OBJECT_DIR / "dbshell"
SEED_DB_PATH = SYSTEM_OBJECT_DBSHELL / "db.sh"
BUILD_DB_SCRIPT = SYSTEM_OBJECT_DIR / "build-db.sh"


def get_system_object_insert_path(ref, category="directory"):
    """Return the path to the per-entity system_object_insert.sql file.

    INSERT files live in each entity's system_description/ folder.
    Groups are stored in ms_system_object_directory/system_description/.
    """
    if ref == "#" or ref is None:
        return SYSTEM_OBJECT_DIR / "system_description"
    return PROJECT_ROOT / "source" / category / f"ms_{ref}" / "system_description" / "01_system_object.sql"


def write_system_object_insert(insert_sql, ref, category="directory"):
    """Write an INSERT to the per-entity system_description/01_system_object.sql file."""
    target_path = get_system_object_insert_path(ref, category)
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(insert_sql + "\n")
    return True, f"INSERT written to {target_path}"


def regenerate_db_sh():
    """Regenerate db.sh from all per-entity system_object_insert.sql files."""
    if not BUILD_DB_SCRIPT.exists():
        return False, f"build-db.sh not found at {BUILD_DB_SCRIPT}"
    result = subprocess.run(["bash", str(BUILD_DB_SCRIPT)], capture_output=True, text=True)
    if result.returncode != 0:
        return False, f"build-db.sh failed: {result.stderr}"
    return True, f"db.sh regenerated ({result.stdout.strip()})"


def append_insert_to_db_sh(insert_sql, ref=None, category="directory"):
    """Write the INSERT to per-entity file and regenerate db.sh.

    Legacy-compatible: if ref is None, falls back to appending directly to db.sh.
    """
    if ref is None:
        # Legacy mode: append directly to db.sh
        if not SEED_DB_PATH.exists():
            return False, f"db.sh not found at {SEED_DB_PATH}"
        content = SEED_DB_PATH.read_text()
        commit_marker = "\n  commit;\nEOSQL"
        if commit_marker in content:
            insert_pos = content.rfind(commit_marker)
            new_content = content[:insert_pos] + "\n" + insert_sql + content[insert_pos + 1:]
        else:
            eosql_marker = "\nEOSQL"
            if eosql_marker in content:
                insert_pos = content.rfind(eosql_marker)
                new_content = content[:insert_pos] + "\n" + insert_sql + "\n" + content[insert_pos:]
            else:
                return False, "Could not find insertion point in db.sh"
        SEED_DB_PATH.write_text(new_content)
        return True, "INSERT appended to db.sh (legacy mode)"
    else:
        # New mode: write per-entity file, then regenerate db.sh
        ok, msg = write_system_object_insert(insert_sql, ref, category)
        if not ok:
            return False, msg
        ok, msg = regenerate_db_sh()
        if not ok:
            return False, msg
        return True, f"INSERT written for '{ref}' and db.sh regenerated"
