#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dnumber              text,
    name                 text,
    description          text,
    id_basis             bigint,
    status               smallint default 1,
	prefix               smallint,
    first_name           text,
    last_name            text,
    middle_name          text,
	id_transaction       text,
	UNIQUE (id, id_basis)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                IS 'Counterparty of the organization';
  COMMENT ON COLUMN ${DB_TABLENAME}.dnumber        IS 'Code of counterparty';
  COMMENT ON COLUMN ${DB_TABLENAME}.name           IS 'Directory name';
  COMMENT ON COLUMN ${DB_TABLENAME}.description    IS 'Directory description';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_basis       IS 'ID basis of counterparty';
  COMMENT ON COLUMN ${DB_TABLENAME}.status         IS 'Directory status (0 - deleted, 1 - saved)';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix         IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix_number  IS 'Prefix number of system object';
  COMMENT ON COLUMN ${DB_TABLENAME}.first_name     IS 'Name';
  COMMENT ON COLUMN ${DB_TABLENAME}.last_name      IS 'Surname';
  COMMENT ON COLUMN ${DB_TABLENAME}.middle_name    IS 'Patronymic';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction IS 'Transaction Id';

EOSQL
