#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ddate            timestamp,
	dnumber          text,
	note             text,
	id_basis         bigint,
	status           smallint default 1,
	id_user          bigint,
	prefix           smallint,
	id_system_object bigint,
	id_transaction   text,
	UNIQUE (id, id_basis)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                  IS 'Business process registration events';
  COMMENT ON COLUMN ${DB_TABLENAME}.ddate            IS 'Document date';
  COMMENT ON COLUMN ${DB_TABLENAME}.dnumber          IS 'Event number';
  COMMENT ON COLUMN ${DB_TABLENAME}.note             IS 'Note';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_basis         IS 'Basis ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.status           IS 'Document status (0 - deleted, 1 - saved, 2 - completed)';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_user          IS 'System user';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix           IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction   IS 'Id transaction';

  CREATE INDEX idx_${DB_TABLENAME}_on_ddate   ON ${DB_TABLENAME}(ddate);
  CREATE INDEX idx_${DB_TABLENAME}_on_status  ON ${DB_TABLENAME}(status);

EOSQL
