#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 text,
    description          text,
    status               smallint default 1,
	prefix               smallint,
	prefix_number        text,
    level                smallint,
    is_group             boolean,
    id_group             bigint,
    ref                  text,
    output_order         smallint,
    icon                 text,
    table_columns        text,
    table_title          text,
    item_title           text,
    item_fields          text,
    on_save_new          text,
    on_save_edit         text,
    on_acceptance        text,
    on_delete            text,
    privileges           text,
    related_documents    text,
    printing_template    text,
    id_transaction       text
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                         IS 'Catalog of system objects';
  COMMENT ON COLUMN ${DB_TABLENAME}.name                    IS 'Directory name';
  COMMENT ON COLUMN ${DB_TABLENAME}.description             IS 'Directory description';
  COMMENT ON COLUMN ${DB_TABLENAME}.status                  IS 'Directory status (0 - deleted, 1 - saved)';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix                  IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix_number           IS 'Prefix number of system object';
  COMMENT ON COLUMN ${DB_TABLENAME}.level                   IS 'Hierarchy level';
  COMMENT ON COLUMN ${DB_TABLENAME}.is_group                IS 'Hierarchy group';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_group                IS 'Hierarchy group Id';
  COMMENT ON COLUMN ${DB_TABLENAME}.ref                     IS 'Endpoint ref';
  COMMENT ON COLUMN ${DB_TABLENAME}.output_order            IS 'Output order';
  COMMENT ON COLUMN ${DB_TABLENAME}.icon                    IS 'Path to PNG';
  COMMENT ON COLUMN ${DB_TABLENAME}.table_columns           IS 'Interface table columns';
  COMMENT ON COLUMN ${DB_TABLENAME}.table_title             IS 'Table window title';
  COMMENT ON COLUMN ${DB_TABLENAME}.item_title              IS 'Item window title';
  COMMENT ON COLUMN ${DB_TABLENAME}.item_fields             IS 'Interface item fields';
  COMMENT ON COLUMN ${DB_TABLENAME}.on_save_new             IS 'Save new item';
  COMMENT ON COLUMN ${DB_TABLENAME}.on_save_edit            IS 'Save edited item';
  COMMENT ON COLUMN ${DB_TABLENAME}.on_acceptance           IS 'Acceptance';
  COMMENT ON COLUMN ${DB_TABLENAME}.on_delete               IS 'Delete item';
  COMMENT ON COLUMN ${DB_TABLENAME}.privileges              IS 'Privileges';
  COMMENT ON COLUMN ${DB_TABLENAME}.related_documents       IS 'Related documents';
  COMMENT ON COLUMN ${DB_TABLENAME}.printing_template       IS 'Printable templates';

--SYSTEM_OBJECT_INSERTS_START
  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Справочники',
    'Справочники',
    1,
    0,
    '',
    0,
    TRUE,
    0,
    '#',
    1,
    'dictionary.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    printing_template,
    id_transaction
  ) values (
    'Документы',
    'Документы',
    1,
    0,
    '',
    0,
    TRUE,
    0,
    '#',
    2,
    'document.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Отчеты',
    'Отчеты',
    1,
    0,
    '',
    0,
    TRUE,
    0,
    '#',
    3,
    'report.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистры данных',
    'Регистры данных',
    1,
    0,
    '',
    0,
    TRUE,
    0,
    '#',
    4,
    'dictionary.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'О программе',
    'О программе',
    1,
    0,
    '',
    0,
    TRUE,
    0,
    '#',
    999,
    'about.png',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Студенты',
    'Студенты',
    1,
    0,
    'СТ-',
    1,
    FALSE,
    1,
    'counterparty_directory',
    2,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "ФИО", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник студентов',
    'Элемент справочника студентов',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true,"required": false },
        { "field": "dnumber", "label": "Код", "hidden": false,"required": false },
        { "field": "name", "label": "ФИО", "hidden": false,"required": true },
        { "field": "description", "label": "Описание", "hidden": false,"required": false},
        { "field": "first_name", "label": "Имя", "hidden": false,"required": true},
        { "field": "last_name", "label": "Фамилия", "hidden": false,"required": true},
        { "field": "middle_name", "label": "Отчество", "hidden": false,"required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Отделы',
    'Отделы',
    1,
    0,
    'ОТ-',
    1,
    FALSE,
    1,
    'department_directory',
    3,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "Название", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник отделов',
    'Элемент справочника отделов',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "dnumber", "label": "Код", "hidden": false, "required": false},
        { "field": "name", "label": "Название", "hidden": false, "required": true},
        { "field": "description", "label": "Описание", "hidden": false, "required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Меры дисциплинарных взысканий',
    '',
    1,
    0,
    'МДО-',
    1,
    FALSE,
    1,
    'disciplinary_measures',
    10,
    'dictionary.png',
    '{
      "columns": [
        {
          "field": "id",
          "label": "",
          "hidden": true
        },
        {
          "field": "dnumber",
          "label": "Код",
          "hidden": false
        },
        {
          "field": "name",
          "label": "Наименование",
          "hidden": false
        },
        {
          "field": "description",
          "label": "Описание",
          "hidden": false
        }
      ]
    }',
    'Справочник мер дисциплинарных взысканий',
    'Меры дисциплинарных взысканий',
    '{
      "fields": [
        {
          "field": "id",
          "label": "",
          "hidden": true,
          "required": true
        },
        {
          "field": "dnumber",
          "label": "Код",
          "hidden": false,
          "required": false
        },
        {
          "field": "name",
          "label": "Наименование",
          "hidden": false,
          "required": false
        },
        {
          "field": "description",
          "label": "Описание",
          "hidden": false,
          "required": false
        }
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Сотрудники',
    'Сотрудники',
    1,
    0,
    'СК-',
    1,
    FALSE,
    1,
    'employee_directory',
    1,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "ФИО", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник сотрудников',
    'Элемент справочника сотрудников',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false},
        { "field": "dnumber", "label": "Код", "hidden": false, "required": false},
        { "field": "name", "label": "ФИО", "hidden": false, "required": true},
        { "field": "description", "label": "Описание", "hidden": false, "required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
    "privileges": [
    { "open_list": "true" },
    { "open_item": "true" },
    { "create": "false" },
    { "edit": "false" },
    { "delete": "false" },
    { "accept": "false" },
    { "create_related_documents": "false" }
    ],
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Должности',
    'Должности',
    1,
    0,
    'ДЛ-',
    1,
    FALSE,
    1,
    'job_title_directory',
    5,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "Название", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник должностей',
    'Элемент справочника должностей',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "dnumber", "label": "Код", "hidden": false, "required": false},
        { "field": "name", "label": "Название", "hidden": false, "required": true},
        { "field": "description", "label": "Описание", "hidden": false, "required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Комитет',
    'Комитет',
    1,
    0,
    'КОМ-',
    1,
    FALSE,
    1,
    'organization_directory',
    6,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "Название", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник коммитетов и подразделений',
    'Элемент справочника коммитетов и подразделений',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "dnumber", "label": "Код", "hidden": false, "required": false},
        { "field": "name", "label": "Название", "hidden": false, "required": true},
        { "field": "description", "label": "Описание", "hidden": false, "required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Причины несогласия ДК',
    '',
    1,
    0,
    'ПНДК-',
    1,
    FALSE,
    1,
    'reasons_for_the_dcs_disagreement',
    10,
    'dictionary.png',
    '{
      "columns": [
        {
          "field": "id",
          "label": "",
          "hidden": true
        },
        {
          "field": "dnumber",
          "label": "Код",
          "hidden": false
        },
        {
          "field": "name",
          "label": "Наименование",
          "hidden": false
        },
        {
          "field": "description",
          "label": "Описание",
          "hidden": false
        }
      ]
    }',
    'Справочник причин несогласия ДК',
    'Причины несогласия ДК',
    '{
      "fields": [
        {
          "field": "id",
          "label": "",
          "hidden": true,
          "required": true
        },
        {
          "field": "dnumber",
          "label": "Код",
          "hidden": false,
          "required": false
        },
        {
          "field": "name",
          "label": "Наименование",
          "hidden": false,
          "required": false
        },
        {
          "field": "description",
          "label": "Описание",
          "hidden": false,
          "required": false
        }
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Пункты ЛНА',
    'Пункты локальных нормативных актов организации',
    1,
    0,
    'ПЛНА-',
    1,
    FALSE,
    1,
    'regulations_clauses_directory',
    4,
    'dictionary.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true},
        { "field": "status", "label": "", "hidden": false},
        { "field": "dnumber", "label": "Код", "hidden": false},
        { "field": "name", "label": "Название", "hidden": false},
        { "field": "description", "label": "Описание", "hidden": false}
      ]
    }',
    'Справочник пунктов ЛНА',
    'Элемент справочника пунктов ЛНА',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "dnumber", "label": "Код", "hidden": false, "required": false},
        { "field": "name", "label": "Название", "hidden": false, "required": true},
        { "field": "description", "label": "Описание", "hidden": false, "required": false}
      ]
    }',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Приём сотрудника',
    'Приём сотрудника',
    1,
    0,
    'ПР-',
    1,
    FALSE,
    2,
    'acceptance_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "last_name", "label": "Фамилия", "hidden": false },
        { "field": "first_name", "label": "Имя", "hidden": false },
        { "field": "middle_name", "label": "Отчество", "hidden": false }
      ]
    }',
    'Журнал документов приёмки сотрудника',
    'Документ приём сотрудника',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "last_name", "label": "Фамилия", "hidden": false, "required": false, "default": "" },
        { "field": "first_name", "label": "Имя", "hidden": false, "required": false, "default": "" },
        { "field": "middle_name", "label": "Отчество", "hidden": false, "required": false, "default": "" },
        { "field": "last_genitive", "label": "Фамилия(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "first_genitive", "label": "Имя(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "middle_genitive", "label": "Отчество(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "last_accusative", "label": "Фамилия(В)", "hidden": false, "required": false, "default": "" },
        { "field": "first_accusative", "label": "Имя(В)", "hidden": false, "required": false, "default": "" },
        { "field": "middle_accusative", "label": "Отчество(В)", "hidden": false, "required": false, "default": "" },
        { "field": "id_vk", "label": "IdVk", "hidden": false, "required": false, "default": 0 },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "acceptance_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "acceptance_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "acceptance_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"id_vk":"id_vk"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "employee_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": {"CONCAT":
                        ["last_name", " ", "first_name", " ", "middle_name"]
                        }
                    },
                    {"vk_id": "vk_id"}
                ],
                "FK": [
                    {"id_employee": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "employee_data_ledger",
                "map": [
                    {"balance":          1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_employee":      "id_employee"},
                    {"first_name":       "first_name"},
                    {"last_name":        "last_name"},
                    {"middle_name":      "middle_name"},
                    {"first_genitive":   "first_genitive"},
                    {"last_genitive":    "last_genitive"},
                    {"middle_genitive":  "middle_genitive"},
                    {"first_accusative": "first_accusative"},
                    {"last_accusative":  "last_accusative"},
                    {"middle_accusative":"middle_accusative"},
                    {"id_vk":            "id_vk"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "acceptance_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "acceptance_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "employee_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "employee_directory",
            "filter": "id_employee",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "acceptance_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "true" },
        { "edit": "true" },
        { "delete": "true" },
        { "accept": "true" },
        { "create_related_documents": "true" }
      ]
    }',
    '{
      "related_documents": [
        { "subordinate_document": [
          { "system_object_id":  1}
        ] }
      ]
    }',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Назначение на должность',
    'Назначение на должность',
    1,
    0,
    'НАД-',
    1,
    FALSE,
    2,
    'appointment_document',
    2,
    'document.png',
    '{
      "columns": [
        { "field": "status", "label": ""},
        { "field": "id", "label": "Код" },
        { "field": "ddate", "label": "Дата"},
        { "field": "dnumber", "label": "Номер"},
        { "field": "note", "label": "Примечание"},
        { "field": "id_department", "label": "Отдел", "end_point": "department_directory"},
        { "field": "id_job_title", "label": "Должность", "end_point": "job_title_directory"}
      ]
    }',
    'Журнал документов назначения на должность',
    'Документ назначения на должность',
    '{
      "fields": [
        { "field": "id", "label": "Код", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false },
        { "field": "id_employee", "label": "Сотрудник", "hidden": false, "required": false, "type": "select", "end_point": "employee_directory" },
        { "field": "id_organization", "label": "Комитет", "hidden": false, "required": false, "type": "select", "end_point": "organization_directory" },
        { "field": "id_department", "label": "Отдел", "hidden": false, "required": false, "type": "select", "end_point": "department_directory" },
        { "field": "id_job_title", "label": "Должность", "hidden": false, "required": false, "type": "select", "end_point": "job_title_directory" },
        { "field": "justification", "label": "Обоснование", "hidden": false, "required": false },
        { "field": "id_user", "label": "IdUser", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "IdBasis", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":0},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "appointment_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "appointment_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "appointment_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "staff_placement_ledger",
                "map": [
                    {"balance":           1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_employee":      "id_employee"},
                    {"id_organization":  "id_organization"},
                    {"id_department":    "id_department"},
                    {"id_job_title":     "id_job_title"},
                    {"id_jastification": "id_jastification"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 4,
                "method": "put",
                "end_point": "appointment_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "appointment_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "staff_placement_ledger",
            "filter": "id_document"
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "appointment_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистрация обращения',
    'Регистрация обращения',
    1,
    0,
    'РО-',
    1,
    FALSE,
    2,
    'create_counterparty_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "last_name", "label": "Фамилия", "hidden": false },
        { "field": "first_name", "label": "Имя", "hidden": false },
        { "field": "middle_name", "label": "Отчество", "hidden": false }
      ]
    }',
    'Журнал документов регистрация обращения',
    'Документ регистрация обращения',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "last_name", "label": "Фамилия", "hidden": false, "required": false, "default": "" },
        { "field": "first_name", "label": "Имя", "hidden": false, "required": false, "default": "" },
        { "field": "middle_name", "label": "Отчество", "hidden": false, "required": false, "default": "" },
        { "field": "last_genitive", "label": "Фамилия(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "first_genitive", "label": "Имя(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "middle_genitive", "label": "Отчество(Р)", "hidden": false, "required": false, "default": "" },
        { "field": "last_accusative", "label": "Фамилия(В)", "hidden": false, "required": false, "default": "" },
        { "field": "first_accusative", "label": "Имя(В)", "hidden": false, "required": false, "default": "" },
        { "field": "middle_accusative", "label": "Отчество(В)", "hidden": false, "required": false, "default": "" },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "create_counterparty_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "create_counterparty_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "create_counterparty_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"id_vk":"id_vk"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "counterparty_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": {"CONCAT":
                        ["last_name", " ", "first_name", " ", "middle_name"]
                        }
                    }
                ],
                "FK": [
                    {"id_counterparty": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "counterparty_data_ledger",
                "map": [
                    {"balance":          1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_counterparty":  "id_counterparty"},
                    {"first_name":       "first_name"},
                    {"last_name":        "last_name"},
                    {"middle_name":      "middle_name"},
                    {"first_genitive":   "first_genitive"},
                    {"last_genitive":    "last_genitive"},
                    {"middle_genitive":  "middle_genitive"},
                    {"first_accusative": "first_accusative"},
                    {"last_accusative":  "last_accusative"},
                    {"middle_accusative":"middle_accusative"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "create_counterparty_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "create_counterparty_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "counterparty_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "counterparty_directory",
            "filter": "id_counterparty",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "create_counterparty_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистрация отдела',
    'Регистрация отдела',
    1,
    0,
    'ПО-',
    1,
    FALSE,
    2,
    'create_department_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "name", "label": "Название", "hidden": false }
      ]
    }',
    'Журнал документов создание отдела',
    'Документ создания отдела',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "name", "label": "Название", "hidden": false, "required": false, "default": "" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "create_department_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "create_department_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "create_department_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "department_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": "name"}
                ],
                "FK": [
                    {"id_department": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "department_data_ledger",
                "map": [
                    {"balance":           1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_department":    "id_department"},
                    {"id_organization":  "id_organization"},
                    {"id_employee":      "id_employee"},
                    {"job_title":        "job_title"},
                    {"name":             "name"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "create_department_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "create_department_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "department_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "department_directory",
            "filter": "id_department",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "create_department_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистрация должности',
    'Регистрация должности',
    1,
    0,
    'НД-',
    1,
    FALSE,
    2,
    'create_job_title_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "name", "label": "Название", "hidden": false }
      ]
    }',
    'Журнал документов создание должности',
    'Документ создания должности',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "name", "label": "Название", "hidden": false, "required": false, "default": "" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "create_job_title_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "create_job_title_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "create_job_title_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "job_title_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": "name"}
                ],
                "FK": [
                    {"id_job_title": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "job_title_data_ledger",
                "map": [
                    {"balance":          1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_job_title":     "id_job_title"},
                    {"name":             "name"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "create_job_title_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "create_job_title_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "job_title_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "job_title_directory",
            "filter": "id_job_title",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "create_job_title_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистрация организации/структуры',
    'Регистрация организации/структуры',
    1,
    0,
    'ПО-',
    1,
    FALSE,
    2,
    'create_organization_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "name", "label": "Название", "hidden": false }
      ]
    }',
    'Журнал документов создание организации/структуры',
    'Документ создания организации/структуры',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "name", "label": "Название", "hidden": false, "required": false, "default": "" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "create_organization_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "create_organization_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "create_organization_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "organization_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": "name"}
                ],
                "FK": [
                    {"id_organization": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "organization_data_ledger",
                "map": [
                    {"balance":          1},
                    {"id_document":      "id"},
                    {"ddate":            "ddate"},
                    {"id_organization":  "id_organization"},
                    {"name":             "name"},
                    {"prefix":           "prefix"},
                    {"id_transaction":   "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "create_organization_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "create_organization_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "organization_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "organization_directory",
            "filter": "id_organization",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "create_organization_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Регистрация пункта ЛНА',
    'Регистрация пункта ЛНА',
    1,
    0,
    'РЛНА-',
    1,
    FALSE,
    2,
    'create_regulations_clauses_document',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id", "label": "", "hidden": true },
        { "field": "status", "label": "", "hidden": false },
        { "field": "ddate", "label": "Дата", "hidden": false },
        { "field": "dnumber", "label": "Номер", "hidden": false },
        { "field": "note", "label": "Примечание", "hidden": false },
        { "field": "name", "label": "Название", "hidden": false }
      ]
    }',
    'Журнал документов создание пункта ЛНА',
    'Документ создания пункта ЛНА',
    '{
      "fields": [
        { "field": "id", "label": "", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "name", "label": "Название", "hidden": false, "required": false, "default": "" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false, "default": "" },
        { "field": "id_user", "label": "", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "", "hidden": true, "required": false, "default": 0 },
        { "field": "prefix", "label": "", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_basis":"id_basis"},
                    {"id_user":"id_user"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "create_regulations_clauses_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
        "action": "onSaveEdit",
        "processing":
        [
            {
                "Step": 1,
                "method": "put",
                "end_point": "document",
                "filter": "id",
                "conditions": [
                    {"status": 1}
                ],
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "create_regulations_clauses_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '{
    "action": "onAcceptance",
        "processing":
        [
            {
                "Step": 1,
                "method": "get",
                "end_point": "create_regulations_clauses_document",
                "filter":"id",
                "conditions":
                [
                    {"status": 1}
                ],
                "FK":
                [
                    {"id": "id"},
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"name":"name"},
                    {"note":"note"},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 2,
                "method": "put",
                "end_point": "document",
                "filter":"id",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":2},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ]
            },
            {
                "Step": 3,
                "method": "post",
                "end_point": "regulations_clauses_directory",
                "map": [
                    {"description": "note"},
                    {"prefix":"prefix"},
                    {"status": 1},
                    {"id_basis": "id"},
                    {"name": "name"}
                ],
                "FK": [
                    {"id_regulations_clauses": "id"}
                ]
            },
            {
                "Step": 4,
                "method": "post",
                "end_point": "regulations_clauses_data_ledger",
                "map": [
                    {"balance":                 1},
                    {"id_document":             "id"},
                    {"ddate":                   "ddate"},
                    {"id_regulations_clauses":  "id_regulations_clauses"},
                    {"name":                    "name"},
                    {"prefix":                  "prefix"},
                    {"id_transaction":          "id_transaction"}
                ]
            },
            {
                "Step": 5,
                "method": "put",
                "end_point": "create_regulations_clauses_document",
                "filter": "id",
                "fields": {
                    "status": 2
                }
            }
        ]
    }',
    '{
    "action":"onDelete",
    "processing":[
        {
            "step": 1,
            "method": "get",
            "end_point": "create_regulations_clauses_document",
            "filter": "id"
        },
        {
            "step": 2,
            "method": "delete",
            "end_point": "regulations_clauses_data_ledger",
            "filter": "id_document"
        },
        {
            "step": 3,
            "method": "put",
            "end_point": "regulations_clauses_directory",
            "filter": "id_regulations_clauses",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 4,
            "method": "put",
            "end_point": "document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        },
        {
            "step": 5,
            "method": "put",
            "end_point": "create_regulations_clauses_document",
            "filter": "id",
            "fields": {
                "status": 0
            }
        }
    ]
    }',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Снятие с должности',
    'Снятие с должности',
    1,
    0,
    'СН-',
    1,
    FALSE,
    2,
    'dismissal_document',
    3,
    'document.png',
    '{
      "columns": [
        { "field": "status", "label": ""},
        { "field": "id", "label": "Код" },
        { "field": "ddate", "label": "Дата"},
        { "field": "dnumber", "label": "Номер"},
        { "field": "note", "label": "Примечание"},
        { "field": "id_department", "label": "Отдел", "end_point": "department_directory"},
        { "field": "id_job_title", "label": "Должность", "end_point": "job_title_directory"}
      ]
    }',
    'Журнал документов снятия с должности',
    'Документ снятия с должности',
    '{
      "fields": [
        { "field": "id", "label": "Код", "hidden": true, "required": false },
        { "field": "ddate", "label": "Дата", "hidden": false, "required": true, "default": "now()" },
        { "field": "dnumber", "label": "Номер", "hidden": false, "required": true, "default": "id" },
        { "field": "note", "label": "Примечание", "hidden": false, "required": false },
        { "field": "id_employee", "label": "Сотрудник", "hidden": false, "required": false, "type": "select", "end_point": "employee_directory" },
        { "field": "id_organization", "label": "Комитет", "hidden": false, "required": false, "type": "select", "end_point": "organization_directory" },
        { "field": "id_department", "label": "Отдел", "hidden": false, "required": false, "type": "select", "end_point": "department_directory" },
        { "field": "id_job_title", "label": "Должность", "hidden": false, "required": false, "type": "select", "end_point": "job_title_directory" },
        { "field": "justification", "label": "Обоснование", "hidden": false, "required": false },
        { "field": "id_user", "label": "IdUser", "hidden": true, "required": false, "default": 1 },
        { "field": "id_basis", "label": "IdBasis", "hidden": true, "required": false, "default": 0 }
      ]
    }',
    '{
        "action": "onSaveNew",
        "processing":
        [
            {
                "Step": 1,
                "method": "post",
                "end_point": "document",
                "map":
                [
                    {"ddate":"ddate"},
                    {"dnumber":"dnumber"},
                    {"note":"note"},
                    {"status":1},
                    {"id_user":1},
                    {"prefix":"prefix"},
                    {"id_transaction":"id_transaction"}
                ],
                "FK":
                [
                    {"id": "id"}
                ]
            },
            {
                "Step": 2,
                "method": "post",
                "end_point": "appointment_document",
                "fields":
                [
                    {"status": 1}
                ]
            }
        ]
    }',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Транзакции по реквизитам отделов',
    'Транзакции по реквизитам отделов',
    1,
    0,
    'ТО-',
    1,
    FALSE,
    4,
    'department_data_ledger',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id_document", "label": "Документ", "end_point": "document_directory"},
        { "field": "ddate", "label": "Дата"},
        { "field": "name", "label": "Наименование"},
        { "field": "id_department", "label": "Отдел"}
      ]
    }',
    'Транзакции по реквизитам отдела',
    '',
    '',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Транзакции по реквизитам сотрудников',
    'Транзакции по реквизитам сотрудников',
    1,
    0,
    'ТР-',
    1,
    FALSE,
    4,
    'employee_data_ledger',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id_document", "label": "Документ", "end_point": "document_directory"},
        { "field": "ddate", "label": "Дата"},
        { "field": "first_name", "label": "Имя"},
        { "field": "last_name", "label": "Фамилия"},
        { "field": "middle_name", "label": "Отчество"},
        { "field": "first_genitive", "label": "Имя (род. падеж)"},
        { "field": "last_genitive", "label": "Фамилия (род. падеж)"},
        { "field": "middle_genitive", "label": "Отчество (род. падеж)"},
        { "field": "first_accusative", "label": "Имя (вин. падеж)"},
        { "field": "last_accusative", "label": "Фамилия (вин. падеж)"},
        { "field": "middle_accusative", "label": "Отчество (вин. падеж)"},
        { "field": "id_vk", "label": "ID VK"},
        { "field": "id_employee", "label": "ID сотрудника"}
      ]
    }',
    'Транзакции по реквизитам сотрудников',
    '',
    '',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Транзакции по реквизитам должностей',
    'Транзакции по реквизитам должностей',
    1,
    0,
    'ТД-',
    1,
    FALSE,
    4,
    'job_title_data_ledger',
    1,
    'document.png',
    '{
      "columns": [
        { "field": "id_document", "label": "Документ", "end_point": "document_directory"},
        { "field": "ddate", "label": "Дата"},
        { "field": "name", "label": "Наименование"},
        { "field": "id_job_title", "label": "Должность"}
      ]
    }',
    'Транзакции по реквизитам должности',
    '',
    '',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );

  insert into ${DB_TABLENAME}
  (
    name,
    description,
    status,
    prefix,
    prefix_number,
    level,
    is_group,
    id_group,
    ref,
    output_order,
    icon,
    table_columns,
    table_title,
    item_title,
    item_fields,
    on_save_new,
    on_save_edit,
    on_acceptance,
    on_delete,
    privileges,
    related_documents,
    printing_template,
    id_transaction
  ) values (
    'Транзакции изменеия штатного расписания',
    'Транзакции изменеия штатного расписания',
    1,
    0,
    'ЭТР-',
    1,
    FALSE,
    4,
    'staff_placement_ledger',
    2,
    'document.png',
    '{
      "columns": [
        { "field": "balance", "label": "", "hidden": false},
        { "field": "id_document", "label": "Документ", "end_point": "document_directory", "hidden": false},
        { "field": "ddate", "label": "Дата", "hidden": false},
        { "field": "id_employee", "label": "Сотрудник", "hidden": false},
        { "field": "id_organization", "label": "Организация", "hidden": false},
        { "field": "id_department", "label": "Отдел", "hidden": false},
        { "field": "id_position", "label": "Должность", "hidden": false},
        { "field": "justification", "label": "Обоснование", "hidden": false}
      ]
    }',
    'Транзакции изменеия штатного расписания',
    '',
    '',
    '',
    '',
    '',
    '',
    '{
      "privileges": [
        { "open_list": "true" },
        { "open_item": "true" },
        { "create": "false" },
        { "edit": "false" },
        { "delete": "false" },
        { "accept": "false" },
        { "create_related_documents": "false" }
      ]
    }',
    '',
    '',
    ''
  );
  commit;
EOSQL
