#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dnumber              text,
    name                 text NOT NULL,
    description          text,
	id_basis             smallint,
    status               smallint default 1,
	prefix               smallint,
	vk_id                bigint NOT NULL,
	id_transaction       text,
	UNIQUE (id, id_basis)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                 IS 'Employee directory';
  COMMENT ON COLUMN ${DB_TABLENAME}.dnumber         IS 'Employee number';
  COMMENT ON COLUMN ${DB_TABLENAME}.name            IS 'Employee name';
  COMMENT ON COLUMN ${DB_TABLENAME}.description     IS 'Employee description';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_basis        IS 'Document Id';
  COMMENT ON COLUMN ${DB_TABLENAME}.status          IS 'Directory status (0 - deleted, 1 - saved)';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix          IS 'Prefix of DB';
  COMMENT ON COLUMN ${DB_TABLENAME}.vk_id           IS 'VK ID';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_transaction  IS 'Transaction Id';

  insert into ${DB_TABLENAME}
  (
    dnumber,
    name,
    description,
    id_basis,
    status,
    prefix,
    vk_id,
    id_transaction
  ) values (
    'СК-0000000001',
    'Administrator',
    'System administrator',
    0,
    1,
    0,
    0,
    ''
  );
  commit;
EOSQL
