#!/bin/bash
psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
  CREATE DATABASE ${DB_NAME};
  CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "${DB_NAME}" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "${DB_USER}" --dbname "${DB_NAME}" <<-EOSQL
  CREATE TABLE public.${DB_TABLENAME} (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	dnumber              text,
    name                 text,
    description          text,
    id_basis             bigint,
    status               smallint default 1,
	prefix               smallint,
	id_transaction       text,
	UNIQUE (id, id_basis)
	);

  COMMENT ON TABLE  ${DB_TABLENAME}                IS 'Directory of organizations';
  COMMENT ON COLUMN ${DB_TABLENAME}.dnumber        IS 'Code of organization';
  COMMENT ON COLUMN ${DB_TABLENAME}.name           IS 'Directory name';
  COMMENT ON COLUMN ${DB_TABLENAME}.description    IS 'Directory description';
  COMMENT ON COLUMN ${DB_TABLENAME}.id_basis       IS 'Document Id';
  COMMENT ON COLUMN ${DB_TABLENAME}.status         IS 'Directory status (0 - deleted, 1 - saved)';
  COMMENT ON COLUMN ${DB_TABLENAME}.prefix         IS 'Prefix of DB';


  insert into ${DB_TABLENAME}
  (
    dnumber,
    name,
    description,
    status,
    id_basis,
    prefix,
    id_transaction
  ) values (
    'КОМ-0000000001',
    'Дисциплинарный комитет',
    'Дисциплинарный комитет',
    1,
    0,
    0,
    ''
  );

  commit;

EOSQL
